################################################################
# Unite
################################################################
[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
hook_post_source = '''
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
call denite#custom#map('normal', "t", '<denite:do_action:tabopen>')
call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', '-f', '--hidden'])
call denite#custom#var('grep', 'command', ['ag', '--follow', '--hidden'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme' # colorscheme一覧 :Unite -auto-preview colorscheme
on_cmd = ['denite']
depends = ['denite']

[[plugins]]
repo = 'Shougo/neomru.vim' # 最近開いたファイルの一覧表示 :Unite file_mru
on_source = ['denite']
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite']
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'osyo-manga/unite-quickfix' # buffer cmd run
on_source = ['denite']
depends = ['denite']

################################################################
# Deoplete
################################################################
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'ujihisa/neco-look' # 英単語候補追加
if = 'has("look")'
on_source = ['deoplete']
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax' # 各filetype補完候補追加
on_source = ['deoplete']
on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim' # vimscript補完
on_source = ['deoplete']
on_i = 1

################################################################
# Text Object
################################################################
[[plugins]]
repo = 'rhysd/vim-textobj-ruby' # ruby block text object 対応 -> r
depends = ['vim-textobj-user']
on_ft = ['ruby']

[[plugins]]
repo = 'deris/vim-textobj-enclosedsyntax' # Ruy and Perl syntax textobj 拡張
depends = ['vim-textobj-user']
on_ft = ['ruby']

################################################################
# Langage
################################################################
[[plugins]]
repo = 'https://github.com/tpope/vim-endwise' # ruby end auto
on_ft = ['ruby']

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim' # ruby local variable highlight
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/smarty-syntax' # smarty syntax highlight
on_ft = ['php']

[[plugins]]
repo = 'vim-scripts/smarty-syntax' # smarty syntax highlight
on_ft = ['php']

################################################################
# Vim拡張
################################################################
[[plugins]]
repo = 'cohama/lexima.vim' # Insert or delete brackets, parens, quotes in pair.
on_i = 1
